image: franzos/ruby-node-gulp-java

cache:
  paths:
  - vendor/

before_script:
- bundle install --path vendor

stages:
- build
- deploy

build:
  stage: build
  script:
  - yarn
  - gulp
  - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    when: on_success
    paths:
    - public
    expire_in: 1h

deploy:
  stage: deploy
  script:
  - export AWS_ACCESS_KEY_ID="$(echo "$AWS_ACCESS_KEY_ID")"
  - export AWS_SECRET_ACCESS_KEY="$(echo "$AWS_SECRET_ACCESS_KEY")"
  - bundle exec s3_website push
  only:
  - master
