title: Q-Windows Malaysia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://q-windows.com.my" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

collections:
- types
- security-level
- testimonial
- products

collections:
  types:
    output: true
    permalink: /type/:path/
  security-level:
  blog:
    output: true
    permalink: /blog/:title/
  products:
    output: true
    permalink: /product/:title/
