title: Q-Windows Malaysia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://q-windows.com.my" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
page_gen-dirs: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
  - gulpfile.js
  - package-lock.json
  - package.json
  - yarn.lock
  - s3_website.yml
  - yarn-error.log

collections:
- types
- security-level
- testimonial

collections:
  types:
    output: true
    permalink: /type/:path/
  security-level:
  blog:
    output: true
    permalink: /blog/:title/

page_gen:
  - data: product_condo
    template: product_condo
    name: url
    dir: window-replacement/condominium
